### ISSUE TITLE
Error found.

### ISSUE THREAD

**Issue by FluffPawz** [RaddyTheBrand/25.NodeJs-Express-EJS-MongoDB--Blog#3]
https://github.com/RaddyTheBrand/25.NodeJs-Express-EJS-MongoDB--Blog/blob/7c5810089e1f1779cb63bf8df5f6df4398326e12/server/routes/main.js#L26

Hello, I am new to coding but, I was following along on a tutorial and found an issue.

Where there is a depreciation **_countDocuments_**  is suggested, in the written repository it is missing **_Post_** in front of it. 

const count = await Post.countDocuments({ });

My code did not work until I fixed this.

**Comment by RaddyTheBrand** [comment]
Thank you!

**Comment by FluffPawz** [comment]
Your tutorials are awesome, I appreciate you!
